fix function

diff --git a/bash/custom_cmd b/bash/custom_cmd
--- a/bash/custom_cmd
+++ b/bash/custom_cmd
@@ -5,6 +5,7 @@ function md5str()
 {
     echo "Calculate simple string: [$1]"; echo -n "MD5: "; echo -n "$1" | md5sum;
 }
+export -f md5str
 
 # make
 ################################################################################
@@ -40,11 +41,13 @@ function make()
 	echo
 	return $ret
 }
+export -f make
 
 function make-target()
 {
 	make -qp | awk -F':' '/^[a-zA-Z0-9][^$#\/\t=]*:([^=]|$)/ {split($1,A,/ /); for(i in A)print A[i]}' | sort -u
 }
+export -f make-target
 
 # 解压
 ################################################################################
@@ -69,7 +72,7 @@ function x() {
     fi
 }
 
-7z-comp()
+function 7z-comp()
 {
 	local comp_package_name=$1
 	local comp_dir=$2
@@ -93,6 +96,10 @@ function x() {
 	cmd="7z a -t7z -m0=lzma2 -mx=9 -mfb=64 -md=32m -ms=on -mhe=on -p'${G7ZP}' $comp_package_name $comp_dir"
 	echo "$cmd"
 	$cmd
+	if [ $? -ne 0 ]; then
+		echo "Compression error."
+		return 1
+	fi
 
 	# fix head: 7F 45 4C 46 01 01 (elf)
 	fix_header=(0x7f 0x45 0x4c 0x46 0x01 0x01)
@@ -101,8 +108,9 @@ function x() {
 		echo "$i:${fix_header[$i]}" | xxd -r - $comp_package_name
 	done
 }
+export -f 7z-comp
 
-7z-decomp()
+function 7z-decomp()
 {
 	local decomp_package_name=$1
 	local decomp_org_package_name="${decomp_package_name}.org"
@@ -132,13 +140,14 @@ function x() {
 	echo "$cmd"
 	$cmd
 }
+export -f 7z-decomp
 
 # 代理
 ################################################################################
 # 命令行配置：系统设置 -> 网络 -> 网络代理
 # gsettings get org.gnome.system.proxy mode  #获取当前模式
 # set, 'none' \ 'manual' \ 'auto'
-proxy_on() {
+function proxy_on() {
 	gsettings set org.gnome.system.proxy.http host '127.0.0.1'
 	gsettings set org.gnome.system.proxy.http port 7890
 	gsettings set org.gnome.system.proxy.https host '127.0.0.1'
@@ -152,7 +161,7 @@ proxy_on() {
 
 	echo "Manage URL: http://clash.razord.top"
 }
-proxy_off() {
+function proxy_off() {
 	gsettings set org.gnome.system.proxy.http host ''
 	gsettings set org.gnome.system.proxy.http port 0
 	gsettings set org.gnome.system.proxy.https host ''
