adjust

diff --git a/bash/custom_bashrc b/bash/custom_bashrc
--- a/bash/custom_bashrc
+++ b/bash/custom_bashrc
@@ -8,44 +8,70 @@ hostname=`hostname`
 HOST1NAME="vanxum02"
 
 function git_branch {
-	branch="`git branch 2>/dev/null | grep "^\*" | sed -e "s/^\*\ //"`"
-	if [ "${branch}" != "" ];then
-		if [ "${branch}" = "(no branch)" ];then
-			branch="(`git rev-parse --short HEAD`...)"
-		fi
-		echo "($branch)"
-	fi
+    branch="`git branch 2>/dev/null | grep "^\*" | sed -e "s/^\*\ //"`"
+    if [ "${branch}" != "" ];then
+        if [ "${branch}" = "(no branch)" ];then
+            branch="(`git rev-parse --short HEAD`...)"
+        fi
+        echo "($branch)"
+    fi
+}
+
+function x() {
+    if [ -f $1 ] ; then
+        case $1 in
+            *.tar.bz2)   tar xjf $1     ;;
+            *.tar.gz)    tar xzf $1     ;;
+            *.bz2)       bunzip2 $1     ;;
+            *.rar)       unrar e $1     ;;
+            *.gz)        gunzip $1      ;;
+            *.tar)       tar xf $1      ;;
+            *.tbz2)      tar xjf $1     ;;
+            *.tgz)       tar xzf $1     ;;
+            *.zip)       unzip $1       ;;
+            *.Z)         uncompress $1  ;;
+            *.7z)        7z x $1        ;;
+            *)     echo "'$1' cannot be extracted via extract()" ;;
+        esac
+    else
+        echo "'$1' is not a valid file"
+    fi
 }
 
 # tmux
 function tmux_init()
 {
-	echo "tmux init"
-	(tmux new -s init_r_session -d)	#终端运行，接收端相关
-	(tmux new -s init_s_session -d)	#后台运行，发送端相关
-	tmux ls | grep "init_r_session" | grep "attached"
-	if [ $? ]; then
-		tmux attach -t init_r_session
-	fi
+    echo "tmux init"
+    (tmux new -s init_r_session -d)	#终端运行，接收端相关
+    (tmux new -s init_s_session -d)	#后台运行，发送端相关
+    tmux ls | grep "init_r_session" | grep "attached"
+    if [ $? ]; then
+        tmux attach -t init_r_session
+    fi
 }
 
 function tmux_startup()
 {
-	echo "tmux_startup TMUX=$TMUX"
-	if which tmux 2>&1 >/dev/null; then
-		test -z "$TMUX" && (tmux attach -t init_s_session || tmux_init)
-	fi
+    echo "tmux_startup TMUX=$TMUX"
+    if which tmux 2>&1 >/dev/null; then
+        test -z "$TMUX" && (tmux attach -t init_s_session || tmux_init)
+    fi
+}
+
+function md5str()
+{ 
+    echo "Calculate simple string: [$1]"; echo -n "MD5: "; echo -n "$1" | md5sum; 
 }
 
 
 # 终端输入提示
 if [ x$hostname = x$HOST1NAME ]; then
-	PS1='\A [\u@\h]\w\n=====>$(git_branch)\$'
-	tmux_startup
+    PS1='\A [\u@\h]\w\n=====>$(git_branch)\$'
+    tmux_startup
 else
-	#PS1='\u@\h \[\033[01;36m\]\W\[\033[01;32m\]$(git_branch)\[\033[00m\]\$ '
-	PS1='\[\e[36m\]\A \[\e[32m\][\u\[\e[31m\]@\[\e[33m\]\h\[\e[32m\]]\w\n=====>\[\033[01;36m\]$(git_branch)\[\e[0m\]\[\e[31m\]\$\[\e[0m\]'
-	#PS1="\[\e[36m\]\A \[\e[32m\][\u\[\e[31m\]@\[\e[33m\]\h\[\e[32m\]]\w\[\e[31m\]\$\[\e[0m\]"
+    #PS1='\u@\h \[\033[01;36m\]\W\[\033[01;32m\]$(git_branch)\[\033[00m\]\$ '
+    PS1='\[\e[36m\]\A \[\e[32m\][\u\[\e[31m\]@\[\e[33m\]\h\[\e[32m\]]\w\n=====>\[\033[01;36m\]$(git_branch)\[\e[0m\]\[\e[31m\]\$\[\e[0m\]'
+    #PS1="\[\e[36m\]\A \[\e[32m\][\u\[\e[31m\]@\[\e[33m\]\h\[\e[32m\]]\w\[\e[31m\]\$\[\e[0m\]"
 fi
 
 
@@ -56,38 +82,14 @@ alias man='viman'
 alias astyle-c='astyle --style=linux --indent=spaces=4 --convert-tabs --pad-oper --unpad-paren --break-blocks=all'  #缩进4个空格
 
 if [ hash colordiff 2> /dev/null ]; then
-	echo "I require colordiff but it's not installed.  Aborting."
+    echo "I require colordiff but it's not installed.  Aborting."
 else
-	alias diff='colordiff'
+    alias diff='colordiff'
 fi
 
 alias ebuild='ssh -X shaowangquan@172.16.200.101'
 alias mbuild='sudo sshfs  shaowangquan@172.16.200.101:/home/shaowangquan /home/wqshao/build-dir -o gid=1000,uid=1000,allow_other'
-
-
-#function
-md5str(){ echo "Calculate simple string: [$1]"; echo -n "MD5: "; echo -n "$1" | md5sum; }
-
-function extract() {
-	if [ -f $1 ] ; then
-		case $1 in
-			*.tar.bz2)   tar xjf $1     ;;
-			*.tar.gz)    tar xzf $1     ;;
-			*.bz2)       bunzip2 $1     ;;
-			*.rar)       unrar e $1     ;;
-			*.gz)        gunzip $1      ;;
-			*.tar)       tar xf $1      ;;
-			*.tbz2)      tar xjf $1     ;;
-			*.tgz)       tar xzf $1     ;;
-			*.zip)       unzip $1       ;;
-			*.Z)         uncompress $1  ;;
-			*.7z)        7z x $1        ;;
-			*)     echo "'$1' cannot be extracted via extract()" ;;
-		esac
-	else
-		echo "'$1' is not a valid file"
-	fi
-}
+alias ydict='ydict'
 
 
 # for tmux
@@ -97,14 +99,12 @@ export TERM="screen-256color"
 # "CTRL-S：挂起终端（XON） "CTRL-Q：恢复终端（XOFF） "要禁止这些键盘映射
 stty -ixon
 
-
-
 echo "Winddoing"
 
 # window10 for ubuntu
 
 uname -a | grep "Microsoft"  >> /dev/null
 if [ $? -eq 0 ]; then
-	echo wqshao | sudo -S service ssh restart && echo "Restart SSH" >> /dev/null
-	tmux
+    echo wqshao | sudo -S service ssh restart && echo "Restart SSH" >> /dev/null
+    tmux
 fi
